#!/usr/bin/env python
#coding:utf8
import os

def searchPath(srcPath, ext):
	dstPath = []
	for root, subdirs, files in os.walk(srcPath)
		for f in files:
			basename, e = os.path.splitext(f)
			if e != ext:
				continue
			
			#만약 확장자가 exr이면 저장
			#아니면 지나간다.

	return seqs

def proxyPath(p):
	"""
	경로를 입력받고 Proxy 경로를 반환한다.
	"/project/circle/in/aces_exr/test/test.0001.exr"
	"/project/circle/in/aces_exr/test_proxy/test.0001.exr"
	"""
	#return p + "_proxy"
	return "/tmp" + p

if __name__ == "__main__":
	root = "/project/circle/in/aces_exr"
	print searchPath(root, "exr")
